name: "bluebell"
mode: "dev"
port: 3022
version: "v0.0.1"
start_time: "2022-09-07"
machine_id: 1
secret: "fawfey2873ry87hahfafo*1827&6"
jwtSecret: "jwt_rion_lucy9876@$3%*20220222"

auth:
  jwt_expire: 72

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 16379
  password: ""
  db: 0
  pool_size: 100